vich_uploader:
    db_driver: orm 

    mappings:
        product_image:
            uri_prefix: /img/vimg
            upload_destination: '%kernel.project_dir%/public/img/vimg'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true